export const Constant = {
  IP_ADDRESS: 'IP_ADDRESS',
  ID: 'ID',
  BRIDGE_NAME: 'BRIDGE_NAME',
  USER_NAME: 'USER_NAME',
  LIGHT_NAME: 'LIGHT_NAME',
  UNAUTHORIZED_USER: 1,
  LINK_BUTTON_NOT_PRESSED: 101,
  FAILURE_EXCEPTION: 1000,
  NO_BRIDGE_FOUND: 1157,
  RANDOM_COLORS: -1,
  FAILED_TO_CONNECT: 'failed to connect to',
};
